"""init

Revision ID: 93cfdc66b259
Revises: 
Create Date: 2025-11-06 18:44:04.655226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93cfdc66b259'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ambiguity_lexicon',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('term', sa.String(length=255), nullable=False),
        sa.Column('type', sa.String(length=50), nullable=False),
        sa.Column('owner_id', sa.String(length=255), nullable=True),
        sa.Column('category', sa.String(length=100), nullable=True),
        sa.Column('added_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('term', 'type', 'owner_id', name='uq_term_type_owner')
    )
    with op.batch_alter_table('ambiguity_lexicon', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ambiguity_lexicon_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ambiguity_lexicon_type'), ['type'], unique=False)

    op.create_table('documents',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('filename', sa.String(length=255), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('owner_id', sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_summaries',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('owner_id', sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=50), nullable=False),
        sa.Column('color', sa.String(length=7), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    op.create_table('user_profiles',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.String(length=255), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('first_name', sa.String(length=100), nullable=False),
        sa.Column('last_name', sa.String(length=100), nullable=False),
        sa.Column('company', sa.String(length=255), nullable=False),
        sa.Column('job_title', sa.String(length=255), nullable=False),
        sa.Column('remaining_tokens', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id')
    )
    op.create_table('contradiction_analyses',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('source_document_id', sa.Integer(), nullable=True),
        sa.Column('owner_id', sa.String(length=255), nullable=True),
        sa.Column('analyzed_at', sa.DateTime(), nullable=True),
        sa.Column('total_conflicts_found', sa.Integer(), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contradiction_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contradiction_analyses_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contradiction_analyses_source_document_id'), ['source_document_id'], unique=False)

    op.create_table('requirements',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('req_id', sa.String(length=50), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=True),
        sa.Column('priority', sa.String(length=50), nullable=True),
        sa.Column('requirement_type', sa.String(length=50), nullable=True),  # <-- Added column
        sa.Column('stakeholders', sa.JSON(), nullable=True),  # <-- NEW COLUMN
        sa.Column('owner_id', sa.String(length=255), nullable=True),
        sa.Column('source_document_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('req_id', 'owner_id', name='uq_requirements_req_id_owner')
    )
    op.create_table('ambiguity_analyses',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('requirement_id', sa.Integer(), nullable=True),
        sa.Column('owner_id', sa.String(length=255), nullable=True),
        sa.Column('original_text', sa.Text(), nullable=False),
        sa.Column('analyzed_at', sa.DateTime(), nullable=True),
        sa.Column('total_terms_flagged', sa.Integer(), nullable=True),
        sa.Column('terms_resolved', sa.Integer(), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ambiguity_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ambiguity_analyses_owner_id'), ['owner_id'], unique=False)

    op.create_table('conflicting_pair',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('analysis_id', sa.Integer(), nullable=True),
        sa.Column('conflict_id', sa.String(length=50), nullable=False),
        sa.Column('reason', sa.Text(), nullable=False),
        sa.Column('conflicting_requirement_ids', sa.JSON(), nullable=False),
        sa.Column('status', sa.String(length=50), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['analysis_id'], ['contradiction_analyses.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conflicting_pair', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conflicting_pair_analysis_id'), ['analysis_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conflicting_pair_status'), ['status'], unique=False)

    op.create_table('requirement_tags',
        sa.Column('requirement_id', sa.Integer(), nullable=False),
        sa.Column('tag_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ),
        sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
        sa.PrimaryKeyConstraint('requirement_id', 'tag_id')
    )
    op.create_table('ambiguous_terms',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('analysis_id', sa.Integer(), nullable=True),
        sa.Column('term', sa.String(length=255), nullable=False),
        sa.Column('position_start', sa.Integer(), nullable=False),
        sa.Column('position_end', sa.Integer(), nullable=False),
        sa.Column('sentence_context', sa.Text(), nullable=True),
        sa.Column('is_ambiguous', sa.Boolean(), nullable=True),
        sa.Column('confidence', sa.Float(), nullable=True),
        sa.Column('reasoning', sa.Text(), nullable=True),
        sa.Column('clarification_prompt', sa.Text(), nullable=True),
        sa.Column('suggested_replacements', sa.JSON(), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['analysis_id'], ['ambiguity_analyses.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ambiguous_terms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ambiguous_terms_analysis_id'), ['analysis_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ambiguous_terms_status'), ['status'], unique=False)

    op.create_table('clarification_history',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('term_id', sa.Integer(), nullable=True),
        sa.Column('requirement_id', sa.Integer(), nullable=True),
        sa.Column('owner_id', sa.String(length=255), nullable=True),
        sa.Column('original_text', sa.Text(), nullable=False),
        sa.Column('clarified_text', sa.Text(), nullable=False),
        sa.Column('action', sa.String(length=50), nullable=False),
        sa.Column('clarified_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['term_id'], ['ambiguous_terms.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clarification_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clarification_history_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clarification_history_requirement_id'), ['requirement_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clarification_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clarification_history_requirement_id'))
        batch_op.drop_index(batch_op.f('ix_clarification_history_owner_id'))

    op.drop_table('clarification_history')
    with op.batch_alter_table('ambiguous_terms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ambiguous_terms_status'))
        batch_op.drop_index(batch_op.f('ix_ambiguous_terms_analysis_id'))

    op.drop_table('ambiguous_terms')
    op.drop_table('requirement_tags')
    with op.batch_alter_table('conflicting_pair', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conflicting_pair_status'))
        batch_op.drop_index(batch_op.f('ix_conflicting_pair_analysis_id'))

    op.drop_table('conflicting_pair')
    with op.batch_alter_table('ambiguity_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ambiguity_analyses_owner_id'))

    op.drop_table('ambiguity_analyses')
    op.drop_table('requirements')
    with op.batch_alter_table('contradiction_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contradiction_analyses_source_document_id'))
        batch_op.drop_index(batch_op.f('ix_contradiction_analyses_owner_id'))

    op.drop_table('contradiction_analyses')
    op.drop_table('user_profiles')
    op.drop_table('tags')
    op.drop_table('project_summaries')
    op.drop_table('documents')
    with op.batch_alter_table('ambiguity_lexicon', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ambiguity_lexicon_type'))
        batch_op.drop_index(batch_op.f('ix_ambiguity_lexicon_owner_id'))

    op.drop_table('ambiguity_lexicon')
    # ### end Alembic commands ###
